### PR TITLE
Add form action to radio buttons.

### PR DESCRIPTION
**Pull request by icyphox**

### CODE REVIEW

**Comment by drakonizer** [comment]
Kinda useless without Potato's new PHPs isn't it? Why don't you commit that or send it to me?

**Comment by icyphox** [comment]
Yeah, he's done with the voting and pic upload PHPs, he's yet to send 'em to me.
Also, I did it with him a couple of times, that's the reason for the delay. Good stuff.

**Comment by drakonizer** [comment]
Are you going to upload it here or will you zip it and email it to me?
Also, that was WAAY too much info for me.

**Comment by icyphox** [comment]
He hasn't sent them yet! And what was way too much info?
I'll be uploading it here, once I get them.

**Comment by drakonizer** [comment]
Read your comment again
Smh

**Comment by icyphox** [comment]
Doesn't seem too hard to understand, you dyslexic bruh?

**Comment by drakonizer** [comment]
Can you please read the comment before I said "waay too much info" over and over again, till you figure out why I said that?

**Comment by icyphox** [comment]
Still don't get it, whatever, he's sent the stuff, filing a pull request.

**Pull request merged**
